name: CI

on:
  push:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: install dependencies
        run: npm install --legacy-peer-deps

      - name: linter
        run: npm run lint
